apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "observability-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "observability-demo.name" . }}
    spec:
      serviceAccountName: {{ include "observability-demo.fullname" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
