apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "observability-demo.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "observability-demo.name" . }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - {}
