apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "observability-demo.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "observability-demo.name" . }}
